### ISSUE TITLE
Still no sound from clementine

### ISSUE THREAD

**Issue by varadgunjal** [suckowbiz/dockerside#2]
I looked at the previous closed issues and have tried all sorts of acrobatics with pulseaudio. However, the container logs still give me : `PulseDeviceFinder:59 Connection to pulseaudio failed`

I even tried passing as an environment variable `--env PULSE_SERVER=tcp:localhost:4713`
and this works for getting sound from Chrome as well.

Any suggestions?

**Comment by suckowbiz** [comment]
Hi, of course the description lacks some details to let me spend my leisure on figuring out why in your setup this does not work. Actually using the provided run script and image Clementine plays sound. I use it daily. There just was an issue when using it together with another container because the sound could not be shared across multiple containers. I just added another flag for the run scripts to have chrome and clementine both playing sound through `/dev/snd`.

I am going to close this issue.
