### ISSUE TITLE
Clementine

### ISSUE THREAD

**Issue by zoltan4929** [suckowbiz/dockerside#3]
Hello Suckowbiz!

I want to install Clementine in a docker container. I found your version on the Docker Hub. Unfortunately, I couldn’t run for more attempts. You can put up a version that I could install into Portainer.io. Eg: you provide the data and I manufacture the container. Or in Docker-compose V2 schema.

Best Regard
Zoltan

**Comment by suckowbiz** [comment]
Hi Zoltan,

especially for Clementine some OS stuff is used to have shared sound. I use Pulseaudio. To set up Pulseaudio e.g. docker compose is not powerful enough, this is why a run script is involved. I describe it in the README.md (https://github.com/suckowbiz/dockerside/blob/master/clementine/README.md). Of course this run script might not succeed in all environments and you might need to create your own one.

I am going to close this issue since in the moment there is nothing to add.
